version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/grpc_example
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - server
    networks:
      - app

  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grpc_example
    ports:
      - "5437:5432"
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
    driver: bridge
